"""DEBUG: bake the 3-Aug jack SCAN (Ethernet_jack_2.0) into the render pipeline's jack frame.

Companion to bake_headA_splat.py, for the jack instead of the plug. The new asset is the
same class as the headA plug scan already in production (62-prop full-SH, ~50% flat
surfels, metric Z-up parent scan) -- it just has never been registered.

    src : .../ethernet/jack_new_3rdAug/Ethernet_jack_2.0/splat.ply
          scan frame, metres, Z-up. The jack sits at x 65.6..95.6, y -186.9..-153.9,
          z -53.6..-21.1 mm with its PORT facing scan +y (dominant face-normal cluster is
          (-0.018, -0.998, -0.054), i.e. within 3.3 deg of +y) and its base on the same
          z ~= -0.054 table plane the headA scan rests on.
    dst : the CAD jack frame that --jack-ply expects, i.e. what cad_jack_registered.ply is:
          port axis +z, mouth plane at z = +0.030, port centred on x = y = 0.
          Drop-in: every existing render_batch_v4 flag (--jack-align-rpy -90 0 0,
          --jack-anchor 0 0 0.018) then applies unchanged.

The rotation is NOT a free parameter. The batch's --jack-align-rpy -90 0 0 is an intrinsic
XYZ euler = Rx(-90), which maps CAD +z -> world +y (mouth toward the arm) and CAD +y ->
world -z (i.e. CAD +y points DOWN in the scene). So the scan's physical up (+z, the parent
scan is Z-up) must land on CAD -y, and the scan's port normal (+y) on CAD +z:

    R = Rx(+90)          scan +y -> CAD +z,  scan +z -> CAD -y,  scan +x -> CAD +x
    v_cad = s . Rz(roll) . R . (v_scan - anchor) + (0, 0, mouth_z)

That derivation is only the FALLBACK. Prefer --matrix, which takes the 4x4 a CloudCompare
point-pair registration against jack_meters.obj emits and pins all six DOF plus the scale at
once. The derived path leaves --roll-deg (0/90/180/270 about the mouth axis) unpinned: the
scan offers no cue for it, the housing being near-square and the port bore too sparsely
reconstructed to read the RJ45 key notch.

SCALE IS NOT 1.0 AND MUST NOT BE ASSUMED. The source is a Nerfstudio reconstruction
("Generated by Nerstudio 1.1.5" in the ply header), so its units are SfM-arbitrary. The raw
scan's faceplate measures 29.0 x 28.8 mm against the CAD jack's 22.4 x 22.6 mm, but that
ratio is a scan-scale artefact, NOT a physical size difference -- do not read it as "the real
jack is 1.28x the CAD part". The 3-Aug-2026 point-pair registration
(newton_cabling/assets/ethernet/jack_v2_ccmatrix.txt) resolved the scale at 0.8193, and the
registered jack then matches the CAD jack's true extents to ~1mm: that IS 1x. Median
scan->jack_meters.obj surface residual afterwards is 0.91mm, against 1.21mm for the
cad_jack_registered.ply currently in production. Never stack scale_jack_splat.py on a
--matrix bake.

f_rest is DROPPED by default (--schema deg0, the 14-property flat layout every other splat
in this scene uses). Reasons, in order: (1) the compositer promotes the WHOLE scene to
SH-16 if any single splat carries SH (gs_compositer.py:132), (2) _apply_transform rotates
positions and quats but NOT the SH coefficients, so a posed full-SH splat carries its
view-dependent lobes in the scan orientation, and (3) tools/strip_arm_sh.py documents
full-SH plys rainbowing in this renderer. --schema sh rotates the coefficients properly if
you want to test it anyway.

    .venv/bin/python tools/bake_jack_v2.py \
        --out newton_cabling/assets/ethernet/jack_v2_registered.ply --preview /tmp/jack_v2.png
"""

from __future__ import annotations

import argparse
import math
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bake_headA_splat import DEG0_PROPS, quat_mul_wxyz, read_ply, sh_rot_matrix, write_ply  # noqa: E402

SRC = ("/home/pandaliza/parallax/gs-sim-vla/scene/assets/objects/ethernet/"
       "jack_new_3rdAug/Ethernet_jack_2.0/splat.ply")
CAD_JACK = ("/home/pandaliza/parallax/gs-sim-vla/scene/assets/objects/ethernet/"
            "cad_jack_registered.ply")
# Scan-frame mouth centre. x,z = centre of the front plate's extent (66.11..95.09 and
# -53.45..-24.66 mm, measured over the 688 surfels whose normal is within 32 deg of +y and
# that sit in front of y = -161.5mm); y = that plate's 90th-percentile depth. The port is
# centred in a keystone faceplate, so the plate centre IS the port centre to within ~1mm.
# Override once a render shows where the plug actually lands.
ANCHOR = (0.08060, -0.15556, -0.03906)
MOUTH_Z = 0.030          # where the anchor lands in the CAD frame (cad_jack_registered's
                         # own mouth plane; the batch's --jack-anchor 0 0 0.018 backs off
                         # 12mm from it for SEAT_AIM_DY)


def rot_x(deg):
    c, s = math.cos(math.radians(deg)), math.sin(math.radians(deg))
    return np.array([[1, 0, 0], [0, c, -s], [0, s, c]], float)


def rot_z(deg):
    c, s = math.cos(math.radians(deg)), math.sin(math.radians(deg))
    return np.array([[c, -s, 0], [s, c, 0], [0, 0, 1]], float)


def mat_to_quat_wxyz(R):
    t = np.trace(R)
    if t > 0:
        w = math.sqrt(1.0 + t) * 0.5
        x = (R[2, 1] - R[1, 2]) / (4 * w)
        y = (R[0, 2] - R[2, 0]) / (4 * w)
        z = (R[1, 0] - R[0, 1]) / (4 * w)
    else:
        i = int(np.argmax(np.diag(R)))
        j, k = (i + 1) % 3, (i + 2) % 3
        s = math.sqrt(1.0 + R[i, i] - R[j, j] - R[k, k]) * 2
        q = [0.0, 0.0, 0.0]
        q[i] = 0.25 * s
        q[j] = (R[j, i] + R[i, j]) / s
        q[k] = (R[k, i] + R[i, k]) / s
        w = (R[k, j] - R[j, k]) / s
        x, y, z = q
    q = np.array([w, x, y, z], float)
    return q / np.linalg.norm(q)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default=SRC)
    ap.add_argument("--out", required=True)
    ap.add_argument("--matrix", default=None,
                    help="4x4 CloudCompare matrix (4 lines of 4 numbers) mapping SCAN-frame "
                         "points -> CAD-frame points. Replaces the --anchor/--roll-deg "
                         "derivation entirely; --scale is then ignored (the matrix carries it). "
                         "Same file format bake_transform_sh.py takes.")
    ap.add_argument("--anchor", type=float, nargs=3, default=ANCHOR,
                    help="scan-frame port-mouth centre, pinned to (0,0,mouth-z) (m)")
    ap.add_argument("--mouth-z", type=float, default=MOUTH_Z)
    ap.add_argument("--roll-deg", type=float, default=0.0,
                    help="extra roll about the mouth axis, applied in the CAD frame")
    ap.add_argument("--scale", type=float, default=1.0,
                    help="uniform scale; the scan is metric so leave at 1.0")
    ap.add_argument("--schema", choices=["deg0", "sh"], default="deg0")
    ap.add_argument("--opacity-floor", type=float, default=0.0,
                    help="drop gaussians whose sigmoid(opacity) is below this (0 = keep all)")
    ap.add_argument("--preview", default=None, help="write an orthographic PNG check")
    args = ap.parse_args()

    data, props = read_ply(args.src)
    cols = {p: np.asarray(data[p], np.float64).copy() for p in props}
    n0 = len(cols["x"])

    keep = np.ones(n0, bool)
    if args.opacity_floor > 0:
        keep = 1.0 / (1.0 + np.exp(-cols["opacity"])) >= args.opacity_floor
        cols = {p: v[keep] for p, v in cols.items()}
    n = len(cols["x"])

    xyz = np.stack([cols["x"], cols["y"], cols["z"]], 1)
    if args.matrix:
        M = np.loadtxt(args.matrix, dtype=float)
        if M.shape != (4, 4):
            raise SystemExit(f"--matrix must be 4x4, got {M.shape}")
        A = M[:3, :3]
        scale = float(np.cbrt(abs(np.linalg.det(A))))
        R = A / scale
        orth = np.abs(R @ R.T - np.eye(3)).max()
        if orth > 1e-3:
            raise SystemExit(f"--matrix rotation block is not a similarity (orthogonality "
                             f"error {orth:.2e}); CloudCompare should emit s*R")
        xyz = xyz @ A.T + M[:3, 3]
        anchor = np.array([np.nan] * 3)
        if abs(scale - 1.0) > 0.01:
            print(f"  note: the matrix carries a {scale:.4f}x scale. That is EXPECTED here -- the "
                  f"Nerfstudio source has SfM-arbitrary units and the registration is what "
                  f"resolves them (0.8193 as of 3 Aug 2026). Check the printed bbox against "
                  f"cad_jack_registered.ply below: matching extents means the result is 1x.")
        args.scale = scale
    else:
        R = rot_z(args.roll_deg) @ rot_x(90.0)
        anchor = np.asarray(args.anchor, float)
        scale = args.scale
        xyz = args.scale * (xyz - anchor) @ R.T + np.array([0.0, 0.0, args.mouth_z])
    cols["x"], cols["y"], cols["z"] = xyz[:, 0], xyz[:, 1], xyz[:, 2]

    q = np.stack([cols[f"rot_{i}"] for i in range(4)], 1)
    q = q / np.linalg.norm(q, axis=1, keepdims=True)
    qr = np.tile(mat_to_quat_wxyz(R), (n, 1))
    q = quat_mul_wxyz(qr, q)
    for i in range(4):
        cols[f"rot_{i}"] = q[:, i]

    if args.scale != 1.0:
        for p in ("scale_0", "scale_1", "scale_2"):
            cols[p] += math.log(args.scale)

    if args.schema == "deg0":
        out_props = DEG0_PROPS
    else:
        out_props = props
        nrest = sum(p.startswith("f_rest_") for p in props)
        if nrest:
            if nrest != 45:
                raise SystemExit(f"--schema sh expects 45 f_rest coeffs, got {nrest}")
            # INRIA channel-major: f_rest reshape(3,15).T -> (15 coeffs, 3 channels)
            rest = np.stack([cols[f"f_rest_{i}"] for i in range(45)], 1).reshape(n, 3, 15)
            out = np.empty_like(rest)
            off = 0
            for band in (1, 2, 3):
                k = 2 * band + 1
                M = sh_rot_matrix(band, R)
                out[:, :, off:off + k] = np.einsum("ij,ncj->nci", M, rest[:, :, off:off + k])
                off += k
            out = out.reshape(n, 45)
            for i in range(45):
                cols[f"f_rest_{i}"] = out[:, i]

    missing = [p for p in out_props if p not in cols]
    if missing:
        raise SystemExit(f"source ply lacks {missing}")
    write_ply(args.out, cols, out_props)

    lo, hi = xyz.min(0), xyz.max(0)
    print(f"wrote {args.out}")
    print(f"  {n} gaussians ({n0 - n} dropped by --opacity-floor), schema {args.schema} "
          f"({len(out_props)} props)")
    if args.matrix:
        print(f"  transform: {args.matrix} (scale {scale:.4f})")
    else:
        print(f"  roll {args.roll_deg:g} deg, scale {args.scale:g}, "
              f"anchor {np.round(anchor, 5).tolist()}")
    print(f"  CAD-frame bbox (mm): {np.round(lo * 1000, 2).tolist()} .. {np.round(hi * 1000, 2).tolist()}")
    print(f"  mouth plane at z={args.mouth_z * 1000:.1f}mm; body should extend toward -z "
          f"(got z {lo[2] * 1000:.1f}..{hi[2] * 1000:.1f}mm)")
    if hi[2] > args.mouth_z + 0.004:
        print("  WARNING: geometry sticks out >4mm in FRONT of the mouth plane -- the anchor "
              "or the roll is probably wrong")
    ref_lo, ref_hi = None, None
    if os.path.exists(CAD_JACK):
        rd, _ = read_ply(CAD_JACK)
        rxyz = np.stack([np.asarray(rd[k], float) for k in "xyz"], 1)
        ref_lo, ref_hi = rxyz.min(0), rxyz.max(0)
        print(f"  cad_jack_registered.ply for reference (mm): "
              f"{np.round(ref_lo * 1000, 2).tolist()} .. {np.round(ref_hi * 1000, 2).tolist()}")

    if args.preview:
        _preview(args.preview, xyz, cols, ref_lo, ref_hi)


def _preview(path, xyz, cols, ref_lo, ref_hi):
    import matplotlib  # noqa: PLC0415
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # noqa: PLC0415

    SH_C0 = 0.28209479177387814
    rgb = np.clip(0.5 + SH_C0 * np.stack([cols[f"f_dc_{i}"] for i in range(3)], 1), 0, 1)
    a = np.clip(1.0 / (1.0 + np.exp(-cols["opacity"])), 0, 1)
    fig, axes = plt.subplots(1, 3, figsize=(15, 5.2))
    for ax, (u, v, nm) in zip(axes, [(0, 1, "down the mouth axis (-z): the PORT"),
                                     (0, 2, "x-z: mouth plane at top"),
                                     (1, 2, "y-z: CAD +y is DOWN in the scene")]):
        order = np.argsort(xyz[:, 3 - u - v] if u + v != 1 else xyz[:, 2])
        ax.scatter(xyz[order, u] * 1000, xyz[order, v] * 1000, s=6,
                   c=np.clip(rgb[order] * 2.4, 0, 1), alpha=a[order] * 0.8, lw=0)
        if ref_lo is not None:
            ax.add_patch(plt.Rectangle((ref_lo[u] * 1000, ref_lo[v] * 1000),
                                       (ref_hi - ref_lo)[u] * 1000, (ref_hi - ref_lo)[v] * 1000,
                                       fill=False, ec="r", lw=1.2, ls="--"))
        ax.set_title(nm, fontsize=9)
        ax.set_xlabel("xyz"[u] + " (mm)")
        ax.set_ylabel("xyz"[v] + " (mm)")
        ax.set_aspect("equal")
        ax.grid(alpha=.3)
        ax.axhline(0, color="0.6", lw=.5)
        ax.axvline(0, color="0.6", lw=.5)
    fig.suptitle("baked jack in the CAD frame (red dashed = cad_jack_registered extent)", fontsize=10)
    plt.tight_layout()
    plt.savefig(path, dpi=110)
    print(f"  preview -> {path}")


if __name__ == "__main__":
    main()
